// Import only the Signavio icons actually used — avoids AllIcons.js overriding UI5 icons (e.g. 'group')
import '@signavio/icons/dist/company-memory.js'
import '@signavio/icons/dist/customer-journey.js'
import '@signavio/icons/dist/pca.js'
import '@signavio/icons/dist/graph-unspecified.js'
import '@signavio/icons/dist/link.js'
import '@signavio/icons/dist/news.js'
import '@signavio/icons/dist/organization.js'
import '@signavio/icons/dist/panel-right.js'
import '@signavio/icons/dist/process-level.js'
import '@signavio/icons/dist/bpmn-type-service.js'
import '@signavio/icons/dist/process-intelligence.js'
import '@signavio/icons/dist/process-manager.js'
import '@signavio/icons/dist/quickmodel.js'
import '@signavio/icons/dist/report.js'
import '@signavio/icons/dist/rocket.js'
import '@signavio/icons/dist/string.js'
import '@signavio/icons/dist/variant.js'
import '@signavio/icons/dist/simulation.js'
import '@signavio/icons/dist/visible-confirmed.js'
import '@signavio/icons/dist/published.js'
import '@signavio/icons/dist/published-changed.js'
import '@signavio/icons/dist/export.js'
import '@signavio/icons/dist/import.js'
import '@signavio/icons/dist/file-move.js'
import '@signavio/icons/dist/invisible.js'
import '@signavio/icons/dist/diagram-dmn.js'
import '@signavio/icons/dist/process-map.js'
import '@signavio/icons/dist/navigation-map.js'
import '@signavio/icons/dist/value-any.js'
import '@signavio/icons/dist/process-data-view.js'
import '@signavio/icons/dist/source-data.js'
// Dictionary category type icons
import '@signavio/icons/dist/activity.js'
import '@signavio/icons/dist/computer.js'
import '@signavio/icons/dist/doc.js'
import '@signavio/icons/dist/risk.js'
import '@signavio/icons/dist/start-event.js'
import '@signavio/icons/dist/overlay-risk-control.js'
import '@signavio/icons/dist/software-license.js'
// BPMN MEP icons
import '@signavio/icons/dist/task-activity.js'
import '@signavio/icons/dist/collapsed-subprocess.js'
import '@signavio/icons/dist/expanded-subprocess.js'
import '@signavio/icons/dist/collapsed-event-subprocess.js'
import '@signavio/icons/dist/event-subprocess.js'
import '@signavio/icons/dist/exclusive-xor-gateway.js'
import '@signavio/icons/dist/event-based-gateway.js'
import '@signavio/icons/dist/parallel-gateway.js'
import '@signavio/icons/dist/inclusive-gateway.js'
import '@signavio/icons/dist/complex-gateway.js'
import '@signavio/icons/dist/pool-lane.js'
import '@signavio/icons/dist/collapsed-pool.js'

import '@signavio/icons/dist/text-annotation.js'
import '@signavio/icons/dist/end-event.js'
import '@signavio/icons/dist/end-message-event.js'
import '@signavio/icons/dist/end-escalation-event.js'
import '@signavio/icons/dist/end-error-event.js'
import '@signavio/icons/dist/cancel-error-event.js'
import '@signavio/icons/dist/end-compensation-event.js'
import '@signavio/icons/dist/end-signal-event.js'
import '@signavio/icons/dist/end-multiple-event.js'
import '@signavio/icons/dist/terminate-end-event.js'
import '@signavio/icons/dist/start-message-event.js'
import '@signavio/icons/dist/start-timer-event.js'
import '@signavio/icons/dist/start-escalation-event.js'
import '@signavio/icons/dist/start-conditional-event.js'
import '@signavio/icons/dist/start-error-event.js'
import '@signavio/icons/dist/start-compensation-event.js'
import '@signavio/icons/dist/start-signal-event.js'
import '@signavio/icons/dist/start-multiple-event.js'
import '@signavio/icons/dist/start-parallel-multiple-event.js'
import '@signavio/icons/dist/catching-intermediate-message-event.js'
import '@signavio/icons/dist/catching-intermediate-timer-event.js'
import '@signavio/icons/dist/catching-intermediate-escalation-event.js'
import '@signavio/icons/dist/catching-intermediate-conditional-event.js'
import '@signavio/icons/dist/catching-intermediate-link-event.js'
import '@signavio/icons/dist/catching-intermediate-error-event.js'
import '@signavio/icons/dist/catching-intermediate-cancel-event.js'
import '@signavio/icons/dist/catching-intermediate-compensation-event.js'
import '@signavio/icons/dist/catching-intermediate-signal-event.js'
import '@signavio/icons/dist/catching-intermediate-multiple-event.js'
import '@signavio/icons/dist/catching-intermediate-parallel-multiple-event.js'
import '@signavio/icons/dist/intermediate-event.js'
import '@signavio/icons/dist/throwing-intermediate-message-event.js'
import '@signavio/icons/dist/throwing-intermediate-escalation-event.js'
import '@signavio/icons/dist/intermediate-link-event.js'
import '@signavio/icons/dist/throwing-intermediate-compensation-event.js'
import '@signavio/icons/dist/throwing-intermediate-signal-event.js'
import '@signavio/icons/dist/throwing-intermediate-multiple-event.js'
import '@signavio/icons/dist/sequence-flow.js'
import '@signavio/icons/dist/association-undirected.js'
import '@signavio/icons/dist/association-unidirectional.js'
import '@signavio/icons/dist/association-bidirectional.js'
import '@signavio/icons/dist/message-flow.js'
import '@signavio/icons/dist/data-indicator.js'
import '@signavio/icons/dist/traffic-light.js'
import '@signavio/icons/dist/gauge-cockpit.js'
import '@signavio/icons/dist/key-measure.js'
import '@signavio/icons/dist/data-trend.js'
import '@signavio/icons/dist/progress-bar.js'
import '@signavio/icons/dist/ring-chart.js'
import '@signavio/icons/dist/manpower.js'
import '@signavio/icons/dist/emotion-positive.js'
import '@signavio/icons/dist/process-data-view.js'
import '@signavio/icons/dist/source-data.js'
// Re-register after UI5 icons to win the SAP-icons-v4/group name conflict
import '@signavio/icons/dist/group.js'
import '@ui5/webcomponents-icons/dist/full-screen.js'
import '@ui5/webcomponents-icons/dist/detail-view.js'
import '@ui5/webcomponents-icons/dist/document-text.js'
import '@ui5/webcomponents-icons/dist/write-new.js'
import '@ui5/webcomponents-icons/dist/share-2.js'
import '@ui5/webcomponents-icons/dist/chain-link.js'
import '@ui5/webcomponents-icons/dist/user-settings.js'
import '@ui5/webcomponents-icons/dist/unfavorite.js'
import '@ui5/webcomponents-icons/dist/favorite.js'
import '@ui5/webcomponents-icons/dist/open-command-field.js'
import '@ui5/webcomponents-icons/dist/bell.js'
import '@signavio/icons/dist/notification-disabled.js'
import '@ui5/webcomponents-icons/dist/feed.js'
import '@ui5/webcomponents-icons/dist/compare.js'
import '@ui5/webcomponents-icons/dist/workflow-tasks.js'
import '@ui5/webcomponents-icons/dist/hint.js'
import '@ui5/webcomponents-icons/dist/show.js'
import '@ui5/webcomponents-icons/dist/source-code.js'
import '@ui5/webcomponents-icons/dist/text.js'
import '@ui5/webcomponents-icons/dist/calendar.js'
import '@ui5/webcomponents-icons/dist/decision.js'
import '@ui5/webcomponents-icons/dist/journey-arrive.js'
import '@ui5/webcomponents-icons/dist/map.js'
import '@ui5/webcomponents-icons/dist/table-row.js'
import '@ui5/webcomponents-icons/dist/number-sign.js'
import '@ui5/webcomponents-icons/dist/multiselect-none.js'
import '@ui5/webcomponents-icons/dist/complete.js'
import '@ui5/webcomponents-icons/dist/family-care.js'
import '@ui5/webcomponents-icons/dist/synchronize.js'
import '@ui5/webcomponents-icons/dist/edit.js'
import '@ui5/webcomponents-icons/dist/move.js'
import '@ui5/webcomponents-icons/dist/copy.js'
import '@ui5/webcomponents-icons/dist/delete.js'
import '@ui5/webcomponents-icons/dist/arrow-top.js'
import '@ui5/webcomponents-icons/dist/arrow-bottom.js'
import '@ui5/webcomponents-icons/dist/da.js'
import '@ui5/webcomponents-icons/dist/ai.js'
import '@ui5/webcomponents-icons/dist/headset.js'
import '@ui5/webcomponents-icons/dist/walk-me.js'
import '@ui5/webcomponents-icons/dist/horizontal-grip.js'
import '@ui5/webcomponents-icons/dist/goal.js'
import '@ui5/webcomponents-icons/dist/checklist.js'
import '@ui5/webcomponents-icons/dist/course-book.js'
import '@ui5/webcomponents-icons/dist/provision.js'
import '@ui5/webcomponents-icons/dist/overflow.js'
import '@ui5/webcomponents-icons/dist/slim-arrow-down.js'
import '@ui5/webcomponents-icons/dist/sort-ascending.js'
import '@ui5/webcomponents-icons/dist/sort-descending.js'
import '@ui5/webcomponents-icons/dist/decline.js'
import '@ui5/webcomponents-icons/dist/status-negative.js'
import '@ui5/webcomponents-icons/dist/message-warning.js'
import '@ui5/webcomponents-icons/dist/email.js'
import '@ui5/webcomponents-icons/dist/image-viewer.js'
import '@ui5/webcomponents-icons/dist/less.js'
import '@ui5/webcomponents-icons/dist/upload.js'
import '@ui5/webcomponents-icons/dist/person-placeholder.js'

// Register the feedback icon SVG under "px-survey" to avoid ShellBar's
// hardcoded sort that forces icon="feedback" to the end of the bar.
import { registerIcon } from '@ui5/webcomponents-base/dist/asset-registries/Icons.js'
import { pathData as pathDatav4, ltr, viewBox } from '@ui5/webcomponents-icons/dist/v4/feedback.js'
import { pathData as pathDatav5 } from '@ui5/webcomponents-icons/dist/v5/feedback.js'
import { pathData as groupPathData, ltr as groupLtr, accData as groupAccData } from '@signavio/icons/dist/group.js'

registerIcon('px-survey', {
  pathData: pathDatav4,
  ltr,
  viewBox,
  collection: 'SAP-icons-v4',
  packageName: '@ui5/webcomponents-icons',
})
registerIcon('px-survey', {
  pathData: pathDatav5,
  ltr,
  viewBox,
  collection: 'SAP-icons-v5',
  packageName: '@ui5/webcomponents-icons',
})
// Force signavio group (dashed box) to win over UI5 group (people) for SAP-icons-v4/group
registerIcon('group', {
  pathData: groupPathData,
  ltr: groupLtr,
  accData: groupAccData,
  collection: 'SAP-icons-v4',
  packageName: '@signavio/icons',
})
// Also register under a conflict-free name
registerIcon('bpmn-group', {
  pathData: groupPathData,
  ltr: groupLtr,
  accData: groupAccData,
  collection: 'SAP-icons-v4',
  packageName: '@signavio/icons',
})
